import { Character } from '../types/character.type';

export const CHARACTER_DATA: Character[] = [
    {
        name: 'CodeMaster',
        race: 'Human',
        currentHP: 180,
        maxHP: 250,
        currentStamina: 8,
        maxStamina: 20,
    },
    {
        name: 'ScriptWizard',
        race: 'Elf',
        currentHP: 150,
        maxHP: 230,
        currentStamina: 12,
        maxStamina: 15,
    },
    {
        name: 'DebugWarrior',
        race: 'Orc',
        currentHP: 220,
        maxHP: 280,
        currentStamina: 10,
        maxStamina: 18,
    },
    {
        name: 'FrontendPaladin',
        race: 'Dwarf',
        currentHP: 200,
        maxHP: 270,
        currentStamina: 14,
        maxStamina: 22,
    },
    {
        name: 'BackendSorcerer',
        race: 'Human',
        currentHP: 160,
        maxHP: 210,
        currentStamina: 6,
        maxStamina: 15,
    },
    {
        name: 'CSSCleric',
        race: 'Gnome',
        currentHP: 120,
        maxHP: 180,
        currentStamina: 5,
        maxStamina: 10,
    },
    {
        name: 'DatabaseRogue',
        race: 'Halfling',
        currentHP: 170,
        maxHP: 220,
        currentStamina: 9,
        maxStamina: 17,
    },
    {
        name: 'FullStackKnight',
        race: 'Human',
        currentHP: 210,
        maxHP: 260,
        currentStamina: 10,
        maxStamina: 19,
    },
    {
        name: 'DevOpsMonk',
        race: 'Elf',
        currentHP: 130,
        maxHP: 200,
        currentStamina: 7,
        maxStamina: 14,
    },
    {
        name: 'APINinja',
        race: 'Orc',
        currentHP: 190,
        maxHP: 240,
        currentStamina: 11,
        maxStamina: 20,
    },
    {
        name: 'CodeMaster',
        race: 'Human',
        currentHP: 180,
        maxHP: 250,
        currentStamina: 8,
        maxStamina: 20,
    },
    {
        name: 'ScriptWizard',
        race: 'Elf',
        currentHP: 150,
        maxHP: 230,
        currentStamina: 12,
        maxStamina: 15,
    },
    {
        name: 'DebugWarrior',
        race: 'Orc',
        currentHP: 220,
        maxHP: 280,
        currentStamina: 10,
        maxStamina: 18,
    },
    {
        name: 'FrontendPaladin',
        race: 'Dwarf',
        currentHP: 200,
        maxHP: 270,
        currentStamina: 14,
        maxStamina: 22,
    },
    {
        name: 'BackendSorcerer',
        race: 'Human',
        currentHP: 160,
        maxHP: 210,
        currentStamina: 6,
        maxStamina: 15,
    },
    {
        name: 'CSSCleric',
        race: 'Gnome',
        currentHP: 120,
        maxHP: 180,
        currentStamina: 5,
        maxStamina: 10,
    },
    {
        name: 'DatabaseRogue',
        race: 'Halfling',
        currentHP: 170,
        maxHP: 220,
        currentStamina: 9,
        maxStamina: 17,
    },
    {
        name: 'FullStackKnight',
        race: 'Human',
        currentHP: 210,
        maxHP: 260,
        currentStamina: 10,
        maxStamina: 19,
    },
    {
        name: 'DevOpsMonk',
        race: 'Elf',
        currentHP: 130,
        maxHP: 200,
        currentStamina: 7,
        maxStamina: 14,
    },
    {
        name: 'APINinja',
        race: 'Orc',
        currentHP: 190,
        maxHP: 240,
        currentStamina: 11,
        maxStamina: 20,
    },
    {
        name: 'CodeMaster',
        race: 'Human',
        currentHP: 180,
        maxHP: 250,
        currentStamina: 8,
        maxStamina: 20,
    },
    {
        name: 'ScriptWizard',
        race: 'Elf',
        currentHP: 150,
        maxHP: 230,
        currentStamina: 12,
        maxStamina: 15,
    },
    {
        name: 'DebugWarrior',
        race: 'Orc',
        currentHP: 220,
        maxHP: 280,
        currentStamina: 10,
        maxStamina: 18,
    },
    {
        name: 'FrontendPaladin',
        race: 'Dwarf',
        currentHP: 200,
        maxHP: 270,
        currentStamina: 14,
        maxStamina: 22,
    },
    {
        name: 'BackendSorcerer',
        race: 'Human',
        currentHP: 160,
        maxHP: 210,
        currentStamina: 6,
        maxStamina: 15,
    },
    {
        name: 'CSSCleric',
        race: 'Gnome',
        currentHP: 120,
        maxHP: 180,
        currentStamina: 5,
        maxStamina: 10,
    },
    {
        name: 'DatabaseRogue',
        race: 'Halfling',
        currentHP: 170,
        maxHP: 220,
        currentStamina: 9,
        maxStamina: 17,
    },
    {
        name: 'FullStackKnight',
        race: 'Human',
        currentHP: 210,
        maxHP: 260,
        currentStamina: 10,
        maxStamina: 19,
    },
    {
        name: 'DevOpsMonk',
        race: 'Elf',
        currentHP: 130,
        maxHP: 200,
        currentStamina: 7,
        maxStamina: 14,
    },
    {
        name: 'APINinja',
        race: 'Orc',
        currentHP: 190,
        maxHP: 240,
        currentStamina: 11,
        maxStamina: 20,
    },
];
